class User:
    def __init__(self):
        self.user_id=None
        self.first_name=None
        self.last_name=None
        self.full_name = None
        self.email = None
        self.password = None
        self.security_question = None
        self.security_answer = None
        self.otp = None
        self.role_id = None
        self.token = None
        self.comment = None
        self.rating = None
        self.color_theme = None
        self.image = None
        self.finanical_aid = None
        self.cgpa = None
        self.gpa =None
        self.finanical_aid = None
        self.middle_name = None
        self.dob = None
        self.gender = None
        self.permanent_address = None
        self.present_address = None
        self.alt_email = None
        self.phone = None
        self.course = None
        self.sem_id=None
